# Data Preprocessing Tools

In [ ]:
# note that the training set like X_train,y_train are the data which we are having in the
# form of dataset and on that data we will train our modle
# we will apply each class of sklearn on our training data and once it has been trained
# testing set like X_test and y_test are the new data  which is not in our data set on which we
# will predict our values
# if the predicted values[test values] are matching with the real test values then our modle is accurate

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
# each and every model of ML in there dataset consistes of two types of data
# 1.features or independent variable
# 2.dependent variable

dataset = pd.read_csv('Data.csv')
print(dataset)
# here x is an features or independent variable[country,age,salary]--> information
# and y is an dependent variable[purchase] --> what we have to predect

# features or independent variable = fratures is bascially is information about a person in a dataset
# information like where he or she lives what's there are what's there salary
# based on that information[features] we will predect whether he will purchase or do some thing which is
# known as dependent variable
# in each and every data set first few columns will be features and last column will be dependent variable
# we will se features or independent variable or dependent variable  through columns wise

# if you want to access the range of columns and range of rows simultaneously then

X = dataset.iloc[:, :-1].values
# if you want to select all the rows from your data set then you can apple dataset.iloc[:]
# dataset is our dataset name then iloc is used to select the indexes of the rows then we are not giving a
# starting value nor ending value in the range iloc[:] by that it will select all the rows from that dataset

# then if you want to select the columns for that selected all rows what we can do is dataset.iloc[:,;]
# just by putting comma[,] we are telling that now its time for columns selection for that rows we have
# previously selected.
y = dataset.iloc[:, -1].values


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
# in this block of code we are trying to replace all the missng values[nan] from
# the dataset

# eg:if we want to replace the nan value from the (salary) column then the strategy we are
# applying is we are taking average of the column and replacing it with the missing value
# to do that we are using  one of the library of sklearn which is  SimpleImputer

from sklearn.impute import SimpleImputer
imputer  = SimpleImputer(missing_values=np.nan, strategy='mean')

# we are taking 'missing_values' attribute from SimpleImputer in order to select the nan value in first parameter
# and in the second parameter we are just generating mean/ average value for that column by using 'strategy' attribute
# as second parameter

# so up until now we have just selected nan value and generted mean values but this our logic has not been linked with
# our dataset in order to link our this logic with the dataset we are using 'fit' method

# after the logic have been linked with dataset we have to replace the nan terms with the logic we have genterated
#because up until now we have just generated mean values but not replace so it to replace nan with mean value we will use
# 'transform' method

# 'fit' will take only the columns which consistes of only numerical values so be care full with that do not apply
# the 'fit' method which consistes of an string column

imputer.fit(X[:,1:3])
# specifying the range of the columns which we want to selecet under 'fit' and transform
X[:,1:3] = imputer.transform(X[:,1:3])
# now this transform will give you a return value and ask which column do you want to replace so thats why we are
# taking column index value x[:,1:3] as a variable name to transform function
# so now our dataset is changing to store that new dataset we are giving x[:,1:3]=

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
# So up until now our data set consistes of Country   Age   Salary Purchased column
# where we have split our data set into 2 categories 1.features or independent variable
# 2.dependent variables after that we have removed all nan values from our data set
# Encoding categorical data:
# so in our dataset there we are having two types of datatypes str and int
# column Country and Purchases consistes of str datatype but a machine learning can only
# take the data which is in the form of int .so we are converting str to int(0 and 1)in this
# Encoding categorical data for that we are using sklearn library

# STEP :1
# we are going to replace country column elements str[france, spain,germany] with int(0 and 1) which is called as
# OneHotEncoding method
# STEP:2
# column Purchased str[yes,no] also contain str values which mean we have to replace then also by int(0 and 1) by
# using OneHotEncoding

# Machine Learning will take only the int values(0,1,2,3,4,5,6,7,8,9) but not str values thats why we are using
# OneHotEncoding method which can transform str to int(0 and 1) values binay values

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer # this is used to  just transform str to int values
from sklearn.preprocessing import OneHotEncoder # this is used to replace that transformed int values with str values

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
#                                         1    |      2        | 3   |            4
# ColumnTransformer is a class
# transformers is an attribute which takes 3 input values
# 1.what kind of transformation you want to do --> ['encoder']
# 2.by which method/class do you want to that -->[OneHotEncoder()]which convert(srt to int)
# 3.name/number of the index values you want to transform
# 4.remainder is an attribute which ask which columns do you does not want to apply transformers
# x = ct.fit_transform(x)
# so now our dataset is changing to store that new dataset we are giving x=
# because x is what we are changing
# fit_transform will return the output in the form of numpy array so it is crucial to have our 'x' also as an np.array
X = np.array(ct.fit_transform(X))
# fit_transform is bascially used to combine our logic with the dataset

In [ ]:
print(X)
# how many different names[[3]=france,spain,Germany] are there in a country column  that many column it will make
# france = 100, spain = 001, germany = 010

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
# so in the dependent variable[Purchased] we are having the data in the form of the str
# now first we have to convert that str to int but if we look closer our dependent variable[Purchased]
# is in the form of binary verctor mean we are having only two outcomes [yes or no] so this mean
# we have to apply LabelEncoder which convert binary outcome str values[yes or no] to [0 and 1]
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
# the point is when ever we are trainig the model its X_train value will be connected
# with y_train values and X_test value will be connected with y_test vaues
# so if we want to predict the training values we can just give regressor.predict(X_train)
# and that X_train will take all the training values from X_train and y_train in the form of 2D array
# same for X_test but if we just give regressor.predict(y_train) that y_train will only take the Training
# values from y which is 1D array

# so the basic idea is if you want to predict the Training data just give regressor.predict(X_train)
# and if you want to predict the test data just give this regressor.predict(X_test)

# and we can only compare real training data with predicted Training data
# and we can only compare real test data with predicted test data

# we could not compare real trainig data with predicted test data because its dimensions will be diffrent

In [ ]:
# so now we are splitting our dataset into 2 categories
# 1.Training set
# 2.Test set
# to do that we are using sklearn.model_selection import train_test_split
# by this we have to split our dataset into 4 categories x_train,x_test,y_train,y_test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2,random_state = 1)
# lets imagine our dataset consistes of 1 unit so 0.2 unit will go under test_size and
# 0.8 will go under training_size
# which mean out of 100% from our dataset we are giving 80% to training our data and 20%
# to test our data
# after splitting our dataset will we randomly split among training set and test set well to make
# sure we have same random factors we are using 'random_state = 1'

In [ ]:
# print(X_train)
print(X_test)
# print(y_train)
print(y_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1]


In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


**Feature** **Scaling**




In [ ]:
# why do we use feature scaling:
# when you observe [x_test] or [x_train] some values are in 'tens' and some of them are in 'thousand'
# which is not good for sacling.
# feature scaling will allow you to put your values neareast to each other between [-3 to 3] or [0 and 1] or [-2 to 2]
# it will allow to put all of our features on the same scale
# why do we need this because in some ML models some feature can be domenated by
# others features in such a way that dominates features are not even considered
# by ML model to put them under the equal scaling we use this

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

# in feature scaling we are having two categories 1.Noramlization 2.Standardization
# you can find formulas for this both in [ML-A-Z-slids][pg:11] but here we dont have to use the
# formulas we just have to write the class name [StandardScaler()] and that's it.
# we can use StandardScaler for each and every case in feature sacling but we can only
# use normalization for a specific case in feature scaling so thats why we are using StandardScaler here
# imp: we should not apply feature scaling on dummy variables [0 and 1]under[Splitting the dataset into
# the Training set and Test set].
# Standardization = x-mean/standard deviation
# transform       |       fit method
# by using fit method we will apply this formula x-mean/standard deviation to x_train
# after that we have to transform that formula
# so we have to do two different things 1.fit=apply formula 2.transform
# but luckely we have a mathos fit_transform() which will do both methods at the same time
# we will apply only transform method to test

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


In [ ]:
# if you look at the output of x_test and x_train you will notice that the output is in 2D array[[]]
# and the class for feature scaling [StandardScaler] only accept the input which are in 2D array
# inputs = x_test and x_train .so check each time is what ever input you are giving is in 2D array
# or not if not then first change it into 2D array